
 
# TEAM_NAME_MAP = {
#     "Arsenal": "Arsenal",
#     "Aston Villa": "Aston Villa",
#     "Bournemouth": "Bournemouth",
#     "Brentford": "Brentford",
#     "Brighton and Hove Albion": "Brighton",
#     "Burnley": "Burnley",
#     "Chelsea": "Chelsea",
#     "Crystal Palace": "Crystal Palace",
#     "Everton": "Everton",
#     "Fulham": "Fulham",
#     "Leeds United": "Leeds",
#     "Leicester City": "Leicester",
#     "Liverpool": "Liverpool",
#     "Manchester City": "Man City",
#     "Manchester United": "Man United",
#     "Newcastle United": "Newcastle",
#     "Nottingham Forest": "Nott'm Forest",
#     "Sheffield United": "Sheffield Utd",
#     "Southampton": "Southampton",
#     "Tottenham Hotspur": "Tottenham",
#     "West Ham United": "West Ham",
#     "Wolverhampton Wanderers": "Wolves",
#     "Sunderland": "Sunderland",
#     "Alavés": "Alaves",
#     "Athletic Bilbao": "Ath Bilbao",
#     "Atlético Madrid": "Ath Madrid",
#     "Barcelona": "Barcelona",
#     "Real Betis": "Betis",
#     "Celta Vigo": "Celta",
#     "Elche CF": "Elche",
#     "Espanyol": "Espanol",
#     "Getafe": "Getafe",
#     "Girona": "Girona",
#     "Granada": "Granada",
#     "Levante": "Levante",
#     "Mallorca": "Mallorca",
#     "CA Osasuna": "Osasuna",
#     "Rayo Vallecano": "Vallecano",
#     "Real Madrid": "Real Madrid",
#     "Real Sociedad": "Sociedad",
#     "Sevilla": "Sevilla",
#     "Valencia": "Valencia",
#     "Villarreal": "Villarreal",
#     "AC Milan": "Milan",
#     "AS Roma": "Roma",
#     "Atalanta BC": "Atalanta",
#     "Bologna": "Bologna",
#     "Cagliari": "Cagliari",
#     "Empoli": "Empoli",
#     "Fiorentina": "Fiorentina",
#     "Genoa": "Genoa",
#     "Hellas Verona": "Verona",
#     "Inter Milan": "Inter",
#     "Juventus": "Juventus",
#     "Lazio": "Lazio",
#     "Lecce": "Lecce",
#     "Monza": "Monza",
#     "Napoli": "Napoli",
#     "Parma": "Parma",
#     "Pisa": "Pisa",
#     "Salernitana": "Salernitana",
#     "Sassuolo": "Sassuolo",
#     "Torino": "Torino",
#     "Udinese": "Udinese",
#     "Como": "Como",
#     "Cremonese": "Cremonese",
#     "Augsburg": "Augsburg",
#     "Bayern Munich": "Bayern Munich",
#     "Borussia Dortmund": "Dortmund",
#     "Eintracht Frankfurt": "Ein Frankfurt",
#     "SC Freiburg": "Freiburg",
#     "TSG Hoffenheim": "Hoffenheim",
#     "Bayer Leverkusen": "Leverkusen",
#     "Borussia Monchengladbach": "M'gladbach",
#     "RB Leipzig": "RB Leipzig",
#     "Union Berlin": "Union Berlin",
#     "VfL Wolfsburg": "Wolfsburg",
#     "FSV Mainz 05": "Mainz",
#     "1. FC Köln": "FC Koln",
#     "VfB Stuttgart": "Stuttgart",
#     "Werder Bremen": "Werder Bremen",
#     "1. FC Heidenheim": "Heidenheim",
#     "Hamburger SV": "Hamburg",
#     "FC St. Pauli": "St Pauli",
#     "Angers": "Angers",
#     "Auxerre": "Auxerre",
#     "Brest": "Brest",
#     "Clermont": "Clermont",
#     "Lille": "Lille",
#     "RC Lens": "Lens",
#     "Lorient": "Lorient",
#     "Olympique Lyonnais": "Lyon",
#     "Olympique de Marseille": "Marseille",
#     "Metz": "Metz",
#     "AS Monaco": "Monaco",
#     "Montpellier": "Montpellier",
#     "Nantes": "Nantes",
#     "Nice": "Nice",
#     "Paris Saint Germain": "Paris SG",
#     "Reims": "Reims",
#     "Rennes": "Rennes",
#     "Strasbourg": "Strasbourg",
#     "Toulouse": "Toulouse",
#     "Le Havre": "Le Havre",
#     "Paris FC": "Paris FC"
# }
TEAM_NAME_MAP = {
    '1. FC Heidenheim': 'Heidenheim',
    '1. FC Köln': 'FC Koln',
    'A. Sebatspor': 'A. Sebatspor',
    'AEK': 'AEK',
    'AFC Telford United': 'AFC Telford United',
    'AFC Wimbledon': 'AFC Wimbledon',
    'AVS': 'AVS',
    'AVS Futebol SAD': 'AVS',
    'AZ Alkmaar': 'AZ Alkmaar',
    'Aachen': 'Aachen',
    'Aalen': 'Aalen',
    'Aalst': 'Aalst',
    'Aberdeen': 'Aberdeen',
    'Academica': 'Academica',
    'Accrington': 'Accrington',
    'Ad. Demirspor': 'Ad. Demirspor',
    'Adanaspor': 'Adanaspor',
    'Ahlen': 'Ahlen',
    'Airdrie': 'Airdrie',
    'Airdrie Utd': 'Airdrie Utd',
    'Ajaccio': 'Ajaccio',
    'Ajaccio GFCO': 'Ajaccio GFCO',
    'Ajax': 'Ajax',
    'Akhisar Belediyespor': 'Akhisar Belediyespor',
    'Akratitos': 'Akratitos',
    'Alanyaspor': 'Alanyaspor',
    'Alaves': 'Alaves',
    'Alavés': 'Alaves',
    'Albacete': 'Albacete',
    'Albinoleffe': 'Albinoleffe',
    'Albion Rvs': 'Albion Rvs',
    'Alcorcon': 'Alcorcon',
    'Alcoyano': 'Alcoyano',
    'Aldershot': 'Aldershot',
    'Alessandria': 'Alessandria',
    'Alfreton Town': 'Alfreton Town',
    'Alicante': 'Alicante',
    'Alloa': 'Alloa',
    'Almere City': 'Almere City',
    'Almeria': 'Almeria',
    'Altay': 'Altay',
    'Altrincham': 'Altrincham',
    'Alverca': 'Alverca',
    'Amiens': 'Amiens',
    'Amorebieta': 'Amorebieta',
    'Ancona': 'Ancona',
    'Anderlecht': 'Anderlecht',
    'Andorra': 'Andorra',
    'Angers': 'Angers',
    'Ankaragucu': 'Ankaragucu',
    'Ankaraspor': 'Ankaraspor',
    'Annan Athletic': 'Annan Athletic',
    'Annecy': 'Annecy',
    'Antalyaspor': 'Antalyaspor',
    'Antwerp': 'Antwerp',
    'Apollon': 'Apollon',
    'Arbroath': 'Arbroath',
    'Arezzo': 'Arezzo',
    'Aris': 'Aris',
    'Arles': 'Arles',
    'Arouca': 'Arouca',
    'Arsenal': 'Arsenal',
    'Ascoli': 'Ascoli',
    'Asteras Tripolis': 'Asteras Tripolis',
    'Aston Villa': 'Aston Villa',
    'Atalanta': 'Atalanta',
    'Atalanta BC': 'Atalanta',
    'Ath Bilbao': 'Ath Bilbao',
    'Ath Bilbao B': 'Ath Bilbao B',
    'Ath Madrid': 'Ath Madrid',
    'Athletic Bilbao': 'Ath Bilbao',
    'Atlético Madrid': 'Ath Madrid',
    'Athens Kallithea': 'Athens Kallithea',
    'Atromitos': 'Atromitos',
    'Augsburg': 'Augsburg',
    'Auxerre': 'Auxerre',
    'Avellino': 'Avellino',
    'Aves': 'Aves',
    'Ayr': 'Ayr',
    'Badajoz': 'Badajoz',
    'Balikesirspor': 'Balikesirspor',
    'Barcelona': 'Barcelona',
    'Barcelona B': 'Barcelona B',
    'Bari': 'Bari',
    'Barnet': 'Barnet',
    'Barnsley': 'Barnsley',
    'Barrow': 'Barrow',
    'Bastia': 'Bastia',
    'Bath City': 'Bath City',
    'Bayer Leverkusen': 'Leverkusen',
    'Bayern Munich': 'Bayern Munich',
    'Beauvais': 'Beauvais',
    'Beerschot VA': 'Beerschot VA',
    'Beira Mar': 'Beira Mar',
    'Belenenses': 'Belenenses',
    'Benevento': 'Benevento',
    'Benfica': 'Benfica',
    'Bergen': 'Bergen',
    'Berwick': 'Berwick',
    'Besiktas': 'Besiktas',
    'Betis': 'Betis',
    'Beveren': 'Beveren',
    'Beziers': 'Beziers',
    'Bielefeld': 'Bielefeld',
    'Birmingham': 'Birmingham',
    'Blackburn': 'Blackburn',
    'Blackpool': 'Blackpool',
    'Boavista': 'Boavista',
    'Bochum': 'Bochum',
    'Bodrumspor': 'Bodrumspor',
    'Bologna': 'Bologna',
    'Bolton': 'Bolton',
    'Bonnyrigg Rose': 'Bonnyrigg Rose',
    'Bordeaux': 'Bordeaux',
    'Boreham Wood': 'Boreham Wood',
    'Borussia Dortmund': 'Dortmund',
    'Borussia Monchengladbach': "M'gladbach",
    'Boston': 'Boston',
    'Boston Utd': 'Boston Utd',
    'Boulogne': 'Boulogne',
    'Bourg Peronnas': 'Bourg Peronnas',
    'Bournemouth': 'Bournemouth',
    'Bradford': 'Bradford',
    'Braintree Town': 'Braintree Town',
    'Braunschweig': 'Braunschweig',
    'Brechin': 'Brechin',
    'Brentford': 'Brentford',
    'Brescia': 'Brescia',
    'Brest': 'Brest',
    'Brighton': 'Brighton',
    'Brighton and Hove Albion': 'Brighton',
    'Bristol City': 'Bristol City',
    'Bristol Rvs': 'Bristol Rvs',
    'Bromley': 'Bromley',
    'Bucaspor': 'Bucaspor',
    'Burghausen': 'Burghausen',
    'Burgos': 'Burgos',
    'Burnley': 'Burnley',
    'Bursaspor': 'Bursaspor',
    'Burton': 'Burton',
    'Bury': 'Bury',
    'Buyuksehyr': 'Buyuksehyr',
    'CA Bastia': 'CA Bastia',
    'CA Osasuna': 'Osasuna',
    'CF Estrela': 'Estrela',
    'CZ Jena': 'CZ Jena',
    'Cadiz': 'Cadiz',
    'Caen': 'Caen',
    'Cagliari': 'Cagliari',
    'Cambridge': 'Cambridge',
    'Cambuur': 'Cambuur',
    'Campomaiorense': 'Campomaiorense',
    'Cannes': 'Cannes',
    'Canvey Island': 'Canvey Island',
    'Cardiff': 'Cardiff',
    'Carlisle': 'Carlisle',
    'Carpi': 'Carpi',
    'Carrarese': 'Carrarese',
    'Cartagena': 'Cartagena',
    'Casa Pia': 'Casa Pia',
    'Castellon': 'Castellon',
    'Catania': 'Catania',
    'Catanzaro': 'Catanzaro',
    'Celta': 'Celta',
    'Celta Vigo': 'Celta',
    'Celtic': 'Celtic',
    'Cercle Brugge': 'Cercle Brugge',
    'Cesena': 'Cesena',
    'Chambly': 'Chambly',
    'Charleroi': 'Charleroi',
    'Charlton': 'Charlton',
    'Chateauroux': 'Chateauroux',
    'Chaves': 'Chaves',
    'Chelsea': 'Chelsea',
    'Cheltenham': 'Cheltenham',
    'Chester': 'Chester',
    'Chesterfield': 'Chesterfield',
    'Chievo': 'Chievo',
    'Chorley': 'Chorley',
    'Cittadella': 'Cittadella',
    'Ciudad de Murcia': 'Ciudad de Murcia',
    'Clermont': 'Clermont',
    'Club Brugge': 'Club Brugge',
    'Clyde': 'Clyde',
    'Clydebank': 'Clydebank',
    'Colchester': 'Colchester',
    'Como': 'Como',
    'Compostela': 'Compostela',
    'Concarneau': 'Concarneau',
    'Cordoba': 'Cordoba',
    'Cosenza': 'Cosenza',
    'Cottbus': 'Cottbus',
    'Cove Rangers': 'Cove Rangers',
    'Coventry': 'Coventry',
    'Cowdenbeath': 'Cowdenbeath',
    'Crawley Town': 'Crawley Town',
    'Cremonese': 'Cremonese',
    'Creteil': 'Creteil',
    'Crewe': 'Crewe',
    'Crotone': 'Crotone',
    'Crystal Palace': 'Crystal Palace',
    'Dag and Red': 'Dag and Red',
    'Darlington': 'Darlington',
    'Darmstadt': 'Darmstadt',
    'Dartford': 'Dartford',
    'Den Bosch': 'Den Bosch',
    'Den Haag': 'Den Haag',
    'Dender': 'Dender',
    'Denizlispor': 'Denizlispor',
    'Derby': 'Derby',
    'Dijon': 'Dijon',
    'Diyarbakirspor': 'Diyarbakirspor',
    'Doncaster': 'Doncaster',
    'Dordrecht': 'Dordrecht',
    'Dorking': 'Dorking',
    'Dortmund': 'Dortmund',
    'Dover Athletic': 'Dover Athletic',
    'Doxa Dramas': 'Doxa Dramas',
    'Dresden': 'Dresden',
    'Droylsden': 'Droylsden',
    'Duisburg': 'Duisburg',
    'Dumbarton': 'Dumbarton',
    'Dundee': 'Dundee',
    'Dundee FC': 'Dundee',
    'Dundee United': 'Dundee United',
    'Dunfermline': 'Dunfermline',
    'Dunkerque': 'Dunkerque',
    'East Fife': 'East Fife',
    'East Stirling': 'East Stirling',
    'Eastbourne Borough': 'Eastbourne Borough',
    'Eastleigh': 'Eastleigh',
    'Ebbsfleet': 'Ebbsfleet',
    'Edinburgh City': 'Edinburgh City',
    'Egaleo': 'Egaleo',
    'Eibar': 'Eibar',
    'Ein Frankfurt': 'Ein Frankfurt',
    'Eintracht Frankfurt': 'Ein Frankfurt',
    'Elazigspor': 'Elazigspor',
    'Elche': 'Elche',
    'Elche CF': 'Elche',
    'Eldense': 'Eldense',
    'Elgin': 'Elgin',
    'Elversberg': 'Elversberg',
    'Empoli': 'Empoli',
    'Erciyesspor': 'Erciyesspor',
    'Ergotelis': 'Ergotelis',
    'Erzgebirge Aue': 'Erzgebirge Aue',
    'Erzurum BB': 'Erzurum BB',
    'Eskisehirspor': 'Eskisehirspor',
    'Espanol': 'Espanol',
    'Espanyol': 'Espanol',
    'Essen': 'Essen',
    'Est Amadora': 'Est Amadora',
    'Estoril': 'Estoril',
    'Estrela': 'Estrela',
    'Eupen': 'Eupen',
    'Everton': 'Everton',
    'Evian Thonon Gaillard': 'Evian Thonon Gaillard',
    'Excelsior': 'Excelsior',
    'Exeter': 'Exeter',
    'Extremadura': 'Extremadura',
    'Extremadura UD': 'Extremadura UD',
    'Eyupspor': 'Eyupspor',
    'FC Brussels': 'FC Brussels',
    'FC Edinburgh': 'FC Edinburgh',
    'FC Emmen': 'FC Emmen',
    'FC Koln': 'FC Koln',
    'FC Porto': 'Porto',
    'FC St. Pauli': 'St Pauli',
    'FC Twente Enschede': 'Twente',
    'FC Utrecht': 'Utrecht',
    'FC Volendam': 'Volendam',
    'FC Zwolle': 'Zwolle',
    'FSV Mainz 05': 'Mainz',
    'Falkirk': 'Falkirk',
    'Falkirk F.C.': 'Falkirk',
    'Famalicao': 'Famalicao',
    'Famalicão': 'Famalicao',
    'Farense': 'Farense',
    'Farsley': 'Farsley',
    'Feirense': 'Feirense',
    'Fenerbahce': 'Fenerbahce',
    'FeralpiSalo': 'FeralpiSalo',
    'Ferrol': 'Ferrol',
    'Feyenoord': 'Feyenoord',
    'Fiorentina': 'Fiorentina',
    'Fleetwood Town': 'Fleetwood Town',
    'For Sittard': 'For Sittard',
    'Forest Green': 'Forest Green',
    'Forfar': 'Forfar',
    'Fortuna Sittard': 'For Sittard',
    'Frankfurt FSV': 'Frankfurt FSV',
    'Freiburg': 'Freiburg',
    'Frosinone': 'Frosinone',
    'Fuenlabrada': 'Fuenlabrada',
    'Fulham': 'Fulham',
    'Fylde': 'Fylde',
    'Galatasaray': 'Galatasaray',
    'Gallipoli': 'Gallipoli',
    'Gateshead': 'Gateshead',
    'Gaziantep': 'Gaziantep',
    'Gaziantepspor': 'Gaziantepspor',
    'Genclerbirligi': 'Genclerbirligi',
    'Genk': 'Genk',
    'Genoa': 'Genoa',
    'Gent': 'Gent',
    'Germinal': 'Germinal',
    'Getafe': 'Getafe',
    'Giannina': 'Giannina',
    'Gil Vicente': 'Gil Vicente',
    'Gillingham': 'Gillingham',
    'Gimnastic': 'Gimnastic',
    'Giresunspor': 'Giresunspor',
    'Girona': 'Girona',
    'Go Ahead Eagles': 'Go Ahead Eagles',
    'Goztep': 'Goztep',
    'Graafschap': 'Graafschap',
    'Granada': 'Granada',
    'Gravesend': 'Gravesend',
    'Grays': 'Grays',
    'Grenoble': 'Grenoble',
    'Gretna': 'Gretna',
    'Greuther Furth': 'Greuther Furth',
    'Grimsby': 'Grimsby',
    'Groningen': 'Groningen',
    'Grosseto': 'Grosseto',
    'Guadalajara': 'Guadalajara',
    'Gubbio': 'Gubbio',
    'Gueugnon': 'Gueugnon',
    'Guimaraes': 'Guimaraes',
    'Guingamp': 'Guingamp',
    'Guiseley': 'Guiseley',
    'Hacettepespor': 'Hacettepespor',
    'Halifax': 'Halifax',
    'Hamburg': 'Hamburg',
    'Hamburger SV': 'Hamburg',
    'Hamilton': 'Hamilton',
    'Hannover': 'Hannover',
    'Hansa Rostock': 'Hansa Rostock',
    'Harelbeke': 'Harelbeke',
    'Harrogate': 'Harrogate',
    'Hartlepool': 'Hartlepool',
    'Hatayspor': 'Hatayspor',
    'Hayes & Yeading': 'Hayes & Yeading',
    'Hearts': 'Hearts',
    'Heerenveen': 'Heerenveen',
    'Heidenheim': 'Heidenheim',
    'Hellas Verona': 'Verona',
    'Heracles': 'Heracles',
    'Heracles Almelo': 'Heracles',
    'Hercules': 'Hercules',
    'Hereford': 'Hereford',
    'Hertha': 'Hertha',
    'Heusden Zolder': 'Heusden Zolder',
    'Hibernian': 'Hibernian',
    'Histon': 'Histon',
    'Hoffenheim': 'Hoffenheim',
    'Holstein Kiel': 'Holstein Kiel',
    'Huddersfield': 'Huddersfield',
    'Huesca': 'Huesca',
    'Hull': 'Hull',
    'Hyde United': 'Hyde United',
    'Ibiza': 'Ibiza',
    'Ingolstadt': 'Ingolstadt',
    'Inter': 'Inter',
    'Inter Milan': 'Inter',
    'Inverness C': 'Inverness C',
    'Ionikos': 'Ionikos',
    'Ipswich': 'Ipswich',
    'Iraklis': 'Iraklis',
    'Istanbulspor': 'Istanbulspor',
    'Istres': 'Istres',
    'Jaen': 'Jaen',
    'Juve Stabia': 'Juve Stabia',
    'Juventus': 'Juventus',
    'Kaiserslautern': 'Kaiserslautern',
    'Kalamaria': 'Kalamaria',
    'Kallithea': 'Kallithea',
    'Kallonis': 'Kallonis',
    'Karabukspor': 'Karabukspor',
    'Karagumruk': 'Karagumruk',
    'Karlsruhe': 'Karlsruhe',
    'Kasimpasa': 'Kasimpasa',
    'Kavala': 'Kavala',
    'Kayserispor': 'Kayserispor',
    'Kelty Hearts': 'Kelty Hearts',
    'Kerkyra': 'Kerkyra',
    'Kettering Town': 'Kettering Town',
    'Kidderminster': 'Kidderminster',
    'Kifisia': 'Kifisia',
    'Kilmarnock': 'Kilmarnock',
    'Koblenz': 'Koblenz',
    'Kocaelispor': 'Kocaelispor',
    'Konyaspor': 'Konyaspor',
    'Kortrijk': 'Kortrijk',
    'La Coruna': 'La Coruna',
    'Lamia': 'Lamia',
    'Larisa': 'Larisa',
    'Las Palmas': 'Las Palmas',
    'Latina': 'Latina',
    'Laval': 'Laval',
    'Lazio': 'Lazio',
    'Le Havre': 'Le Havre',
    'Le Mans': 'Le Mans',
    'Lecce': 'Lecce',
    'Lecco': 'Lecco',
    'Leeds': 'Leeds',
    'Leeds United': 'Leeds',
    'Leganes': 'Leganes',
    'Leicester': 'Leicester',
    'Leicester City': 'Leicester',
    'Leiria': 'Leiria',
    'Leixoes': 'Leixoes',
    'Lens': 'Lens',
    'Leonesa': 'Leonesa',
    'Levadeiakos': 'Levadeiakos',
    'Levante': 'Levante',
    'Leverkusen': 'Leverkusen',
    'Lewes': 'Lewes',
    'Leyton Orient': 'Leyton Orient',
    'Libourne': 'Libourne',
    'Lierse': 'Lierse',
    'Lille': 'Lille',
    'Lincoln': 'Lincoln',
    'Liverpool': 'Liverpool',
    'Livingston': 'Livingston',
    'Livorno': 'Livorno',
    'Llagostera': 'Llagostera',
    'Lleida': 'Lleida',
    'Logrones': 'Logrones',
    'Lokeren': 'Lokeren',
    'Lommel': 'Lommel',
    'Lorca': 'Lorca',
    'Lorient': 'Lorient',
    'Louvieroise': 'Louvieroise',
    'Lugo': 'Lugo',
    'Luton': 'Luton',
    'Lyon': 'Lyon',
    "M'gladbach": "M'gladbach",
    'Macclesfield': 'Macclesfield',
    'Magdeburg': 'Magdeburg',
    'Maidenhead': 'Maidenhead',
    'Maidstone': 'Maidstone',
    'Mainz': 'Mainz',
    'Malaga': 'Malaga',
    'Malaga B': 'Malaga B',
    'Malatyaspor': 'Malatyaspor',
    'Mallorca': 'Mallorca',
    'Man City': 'Man City',
    'Man United': 'Man United',
    'Manchester City': 'Man City',
    'Manchester United': 'Man United',
    'Manisaspor': 'Manisaspor',
    'Mansfield': 'Mansfield',
    'Mantova': 'Mantova',
    'Maritimo': 'Maritimo',
    'Marseille': 'Marseille',
    'Martigues': 'Martigues',
    'Mechelen': 'Mechelen',
    'Mersin Idman Yurdu': 'Mersin Idman Yurdu',
    'Messina': 'Messina',
    'Metz': 'Metz',
    'Middlesbrough': 'Middlesbrough',
    'Milan': 'Milan',
    'Millwall': 'Millwall',
    'Milton Keynes Dons': 'Milton Keynes Dons',
    'Mirandes': 'Mirandes',
    'Modena': 'Modena',
    'Molenbeek': 'Molenbeek',
    'Monaco': 'Monaco',
    'Montpellier': 'Montpellier',
    'Montrose': 'Montrose',
    'Monza': 'Monza',
    'Morecambe': 'Morecambe',
    'Moreirense': 'Moreirense',
    'Moreirense FC': 'Moreirense',
    'Morton': 'Morton',
    'Motherwell': 'Motherwell',
    'Mouscron': 'Mouscron',
    'Mouscron-Peruwelz': 'Mouscron-Peruwelz',
    'Munich 1860': 'Munich 1860',
    'Murcia': 'Murcia',
    'NAC Breda': 'NAC Breda',
    'NEC Nijmegen': 'Nijmegen',
    'Nacional': 'Nacional',
    'Nancy': 'Nancy',
    'Nantes': 'Nantes',
    'Napoli': 'Napoli',
    'Naval': 'Naval',
    'Newcastle': 'Newcastle',
    'Newcastle United': 'Newcastle',
    'Newport County': 'Newport County',
    'Nice': 'Nice',
    'Nijmegen': 'Nijmegen',
    'Niki Volos': 'Niki Volos',
    'Nimes': 'Nimes',
    'Niort': 'Niort',
    'Nocerina': 'Nocerina',
    'Northampton': 'Northampton',
    'Northwich': 'Northwich',
    'Norwich': 'Norwich',
    "Nott'm Forest": "Nott'm Forest",
    'Nottingham Forest': "Nott'm Forest",
    'Notts County': 'Notts County',
    'Novara': 'Novara',
    'Numancia': 'Numancia',
    'Nuneaton Town': 'Nuneaton Town',
    'Nurnberg': 'Nurnberg',
    'OFI': 'OFI',
    'OFI Crete': 'OFI Crete',
    'Oberhausen': 'Oberhausen',
    'Offenbach': 'Offenbach',
    'Oftasspor': 'Oftasspor',
    'Oldham': 'Oldham',
    'Olhanense': 'Olhanense',
    'Olympiakos': 'Olympiakos',
    'Olympiakos Volou': 'Olympiakos Volou',
    'Olympique Lyonnais': 'Lyon',
    'Olympique de Marseille': 'Marseille',
    'Oostende': 'Oostende',
    'Orduspor': 'Orduspor',
    'Orleans': 'Orleans',
    'Osasuna': 'Osasuna',
    'Osmanlispor': 'Osmanlispor',
    'Osnabruck': 'Osnabruck',
    'Oud-Heverlee Leuven': 'Oud-Heverlee Leuven',
    'Oviedo': 'Oviedo',
    'Oxford': 'Oxford',
    'Oxford City': 'Oxford City',
    'PAOK': 'PAOK',
    'PSV Eindhoven': 'PSV Eindhoven',
    'Pacos Ferreira': 'Pacos Ferreira',
    'Paderborn': 'Paderborn',
    'Padova': 'Padova',
    'Palermo': 'Palermo',
    'Panathinaikos': 'Panathinaikos',
    'Panetolikos': 'Panetolikos',
    'Panionios': 'Panionios',
    'Panserraikos': 'Panserraikos',
    'Panthrakikos': 'Panthrakikos',
    'Paris FC': 'Paris FC',
    'Paris SG': 'Paris SG',
    'Paris Saint Germain': 'Paris SG',
    'Parma': 'Parma',
    'Partick': 'Partick',
    'Pau FC': 'Pau FC',
    'Penafiel': 'Penafiel',
    'Pendikspor': 'Pendikspor',
    'Perugia': 'Perugia',
    'Pescara': 'Pescara',
    'Peterboro': 'Peterboro',
    'Peterhead': 'Peterhead',
    'Piacenza': 'Piacenza',
    'Pisa': 'Pisa',
    'Pistoiese': 'Pistoiese',
    'Platanias': 'Platanias',
    'Plymouth': 'Plymouth',
    'Poli Ejido': 'Poli Ejido',
    'Ponferradina': 'Ponferradina',
    'Pontevedra': 'Pontevedra',
    'Pordenone': 'Pordenone',
    'Port Vale': 'Port Vale',
    'Portimonense': 'Portimonense',
    'Porto': 'Porto',
    'Portogruaro': 'Portogruaro',
    'Portsmouth': 'Portsmouth',
    'Preston': 'Preston',
    'Preußen Münster': 'Preußen Münster',
    'Pro Vercelli': 'Pro Vercelli',
    'QPR': 'QPR',
    'Queen of Sth': 'Queen of Sth',
    'Queens Park': 'Queens Park',
    'Quevilly Rouen': 'Quevilly Rouen',
    'RB Leipzig': 'RB Leipzig',
    'RC Lens': 'Lens',
    'RWD Molenbeek': 'RWD Molenbeek',
    'Raith Rvs': 'Raith Rvs',
    'Rangers': 'Rangers',
    'Ravenna': 'Ravenna',
    'Rayo Majadahonda': 'Rayo Majadahonda',
    'Rayo Vallecano': 'Vallecano',
    'Reading': 'Reading',
    'Real Betis': 'Betis',
    'Real Madrid': 'Real Madrid',
    'Real Madrid B': 'Real Madrid B',
    'Real Sociedad': 'Sociedad',
    'Real Union': 'Real Union',
    'Recreativo': 'Recreativo',
    'Red Star': 'Red Star',
    'Regensburg': 'Regensburg',
    'Reggiana': 'Reggiana',
    'Reggina': 'Reggina',
    'Reims': 'Reims',
    'Rennes': 'Rennes',
    'Reus Deportiu': 'Reus Deportiu',
    'Rimini': 'Rimini',
    'Rio Ave': 'Rio Ave',
    'Rizespor': 'Rizespor',
    'Rochdale': 'Rochdale',
    'Roda': 'Roda',
    'Roda JC': 'Roda JC',
    'Rodez': 'Rodez',
    'Roeselare': 'Roeselare',
    'Roma': 'Roma',
    'Roosendaal': 'Roosendaal',
    'Ross County': 'Ross County',
    'Rotherham': 'Rotherham',
    'Rushden & D': 'Rushden & D',
    'SC Freiburg': 'Freiburg',
    'SC Telstar': 'SC Telstar',
    'Saarbrucken': 'Saarbrucken',
    'Sabadell': 'Sabadell',
    'Sakaryaspor': 'Sakaryaspor',
    'Salamanca': 'Salamanca',
    'Salernitana': 'Salernitana',
    'Salford': 'Salford',
    'Salgueiros': 'Salgueiros',
    'Salisbury': 'Salisbury',
    'Sampdoria': 'Sampdoria',
    'Samsunspor': 'Samsunspor',
    'Sandhausen': 'Sandhausen',
    'Santa Clara': 'Santa Clara',
    'Santander': 'Santander',
    'Sassuolo': 'Sassuolo',
    'Scarborough': 'Scarborough',
    'Schalke 04': 'Schalke 04',
    'Scunthorpe': 'Scunthorpe',
    'Sedan': 'Sedan',
    'Seraing': 'Seraing',
    'Sete': 'Sete',
    'Setubal': 'Setubal',
    'Sevilla': 'Sevilla',
    'Sevilla B': 'Sevilla B',
    'Sheffield United': 'Sheffield Utd',
    'Sheffield Weds': 'Sheffield Weds',
    'Shrewsbury': 'Shrewsbury',
    'Siegen': 'Siegen',
    'Siena': 'Siena',
    'Sivasspor': 'Sivasspor',
    'Sochaux': 'Sochaux',
    'Sociedad': 'Sociedad',
    'Sociedad B': 'Sociedad B',
    'Solihull': 'Solihull',
    'Southampton': 'Southampton',
    'Southend': 'Southend',
    'Southport': 'Southport',
    'Sp Braga': 'Sp Braga',
    'Sp Gijon': 'Sp Gijon',
    'Sp Lisbon': 'Sp Lisbon',
    'Spal': 'Spal',
    'Sparta': 'Sparta',
    'Sparta Rotterdam': 'Sparta Rotterdam',
    'Spartans': 'Spartans',
    'Spezia': 'Spezia',
    'Sporting Lisbon': 'Sp Lisbon',
    'St Etienne': 'St Etienne',
    'St Johnstone': 'St Johnstone',
    'St Mirren': 'St Mirren',
    'St Pauli': 'St Pauli',
    'St Truiden': 'St Truiden',
    'St. Albans': 'St. Albans',
    'St. Gilloise': 'St. Gilloise',
    'Stafford Rangers': 'Stafford Rangers',
    'Standard': 'Standard',
    'Stenhousemuir': 'Stenhousemuir',
    'Stevenage': 'Stevenage',
    'Stirling': 'Stirling',
    'Stockport': 'Stockport',
    'Stoke': 'Stoke',
    'Stranraer': 'Stranraer',
    'Strasbourg': 'Strasbourg',
    'Stuttgart': 'Stuttgart',
    'Sudtirol': 'Sudtirol',
    'Sunderland': 'Sunderland',
    'Sutton': 'Sutton',
    'Swansea': 'Swansea',
    'Swindon': 'Swindon',
    'TSG Hoffenheim': 'Hoffenheim',
    'Tamworth': 'Tamworth',
    'Telford United': 'Telford United',
    'Tenerife': 'Tenerife',
    'Ternana': 'Ternana',
    'Terrassa': 'Terrassa',
    'Thrasyvoulos': 'Thrasyvoulos',
    'Tondela': 'Tondela',
    'Torino': 'Torino',
    'Torquay': 'Torquay',
    'Tottenham': 'Tottenham',
    'Tottenham Hotspur': 'Tottenham',
    'Toulouse': 'Toulouse',
    'Tours': 'Tours',
    'Trabzonspor': 'Trabzonspor',
    'Tranmere': 'Tranmere',
    'Trapani': 'Trapani',
    'Treviso': 'Treviso',
    'Triestina': 'Triestina',
    'Trofense': 'Trofense',
    'Troyes': 'Troyes',
    'Tubize': 'Tubize',
    'Twente': 'Twente',
    'U.Las Palmas': 'U.Las Palmas',
    'UCAM Murcia': 'UCAM Murcia',
    'Udinese': 'Udinese',
    'Ulm': 'Ulm',
    'Umraniyespor': 'Umraniyespor',
    'Uniao Madeira': 'Uniao Madeira',
    'Union Berlin': 'Union Berlin',
    'Unterhaching': 'Unterhaching',
    'Utrecht': 'Utrecht',
    'VVV Venlo': 'VVV Venlo',
    'Valencia': 'Valencia',
    'Valenciennes': 'Valenciennes',
    'Valladolid': 'Valladolid',
    'Vallecano': 'Vallecano',
    'Vannes': 'Vannes',
    'Varese': 'Varese',
    'Varzim': 'Varzim',
    'Vecindario': 'Vecindario',
    'Venezia': 'Venezia',
    'Veria': 'Veria',
    'Verona': 'Verona',
    'Vicenza': 'Vicenza',
    'Villarreal': 'Villarreal',
    'Villarreal B': 'Villarreal B',
    'Virtus Entella': 'Virtus Entella',
    'Virtus Lanciano': 'Virtus Lanciano',
    'Vitesse': 'Vitesse',
    'Vitória SC': 'Guimaraes',
    'Vizela': 'Vizela',
    'Volendam': 'Volendam',
    'Volos NFC': 'Volos NFC',
    'VfB Stuttgart': 'Stuttgart',
    'VfL Wolfsburg': 'Wolfsburg',
    'Waalwijk': 'Waalwijk',
    'Waasland-Beveren': 'Waasland-Beveren',
    'Walsall': 'Walsall',
    'Waregem': 'Waregem',
    'Wasquehal': 'Wasquehal',
    'Watford': 'Watford',
    'Wealdstone': 'Wealdstone',
    'Wehen': 'Wehen',
    'Welling United': 'Welling United',
    'Werder Bremen': 'Werder Bremen',
    'West Brom': 'West Brom',
    'West Ham': 'West Ham',
    'West Ham United': 'West Ham',
    'Westerlo': 'Westerlo',
    'Weymouth': 'Weymouth',
    'Wigan': 'Wigan',
    'Willem II': 'Willem II',
    'Wimbledon': 'Wimbledon',
    'Woking': 'Woking',
    'Wolfsburg': 'Wolfsburg',
    'Wolverhampton Wanderers': 'Wolves',
    'Wolves': 'Wolves',
    'Wrexham': 'Wrexham',
    'Wurzburger Kickers': 'Wurzburger Kickers',
    'Wycombe': 'Wycombe',
    'Xanthi': 'Xanthi',
    'Xerez': 'Xerez',
    'Yeni Malatyaspor': 'Yeni Malatyaspor',
    'Yeovil': 'Yeovil',
    'York': 'York',
    'Yozgatspor': 'Yozgatspor',
    'Zaragoza': 'Zaragoza',
    'Zwolle': 'Zwolle'
}

def normalize_team_name(api_name):
    return TEAM_NAME_MAP.get(api_name, api_name)

